import React, { useState } from "react";
import { 
  Award, 
  FileText, 
  Sparkles, 
  Download, 
  Check, 
  RefreshCw, 
  Printer, 
  Info, 
  CheckCircle, 
  Edit3, 
  Clipboard, 
  FileCode, 
  CheckSquare, 
  Save, 
  Eye 
} from "lucide-react";

interface Props {
  selectedProjectTitle: string;
  selectedProjectDomain: string;
}

export default function ResumeDocumentationHelper({ selectedProjectTitle, selectedProjectDomain }: Props) {
  const [name, setName] = useState("");
  const [college, setCollege] = useState("");
  const [domain, setDomain] = useState(selectedProjectDomain || "");
  const [projectTitle, setProjectTitle] = useState(selectedProjectTitle || "");
  const [academicScore, setAcademicScore] = useState("GPA 3.8/4.0");
  const [coreSkills, setCoreSkills] = useState("");
  const [loading, setLoading] = useState(false);
  const [loadingSynopsis, setLoadingSynopsis] = useState(false);

  // Resume results state
  const [summary, setSummary] = useState("");
  const [bullets, setBullets] = useState<string[]>([]);
  const [layoutAdvice, setLayoutAdvice] = useState("");

  // Synopsis state
  const [synopsisText, setSynopsisText] = useState("");

  // Navigation and Interactive state
  const [activeTab, setActiveTab] = useState<"resume" | "synopsis">("resume");
  const [isEditingResume, setIsEditingResume] = useState(false);
  const [isEditingSynopsis, setIsEditingSynopsis] = useState(false);
  const [copiedText, setCopiedText] = useState<"copied" | "latex" | "synopsis" | null>(null);

  // Style templates for CV
  const [cvTheme, setCvTheme] = useState<"harvard" | "tech" | "executive">("harvard");

  React.useEffect(() => {
    if (selectedProjectTitle) {
      setProjectTitle(selectedProjectTitle);
    }
  }, [selectedProjectTitle]);

  React.useEffect(() => {
    if (selectedProjectDomain) {
      setDomain(selectedProjectDomain);
    }
  }, [selectedProjectDomain]);

  const handleGenerateResume = async () => {
    if (!name.trim() || !projectTitle.trim()) {
      alert("Name and Project Title are required to structure the dissertation digest resume!");
      return;
    }
    setLoading(true);
    try {
      const res = await fetch("/api/resume-helper", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name,
          domain,
          projectTitle,
          academicScore,
          coreSkills
        })
      });
      const data = await res.json();
      if (data) {
        setSummary(data.summary || "");
        setBullets(data.projectBullets || []);
        setLayoutAdvice(data.structuralAdvice || "");
        setActiveTab("resume");
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleGenerateSynopsis = async () => {
    if (!projectTitle.trim()) {
      alert("Please specify a project topic first!");
      return;
    }
    setLoadingSynopsis(true);
    try {
      const res = await fetch("/api/generate-report", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          topic: projectTitle,
          domain,
          section: "Abstract"
        })
      });
      const data = await res.json();
      if (data.content) {
        const syn_layout = `PROJECT SYNOPSIS DOCUMENT PROPOSAL
---------------------------------------------
SUBJECT TOPIC: ${projectTitle.toUpperCase()}
DOMAIN: ${domain || "General Academics"}
ACADEMIC SUBSTANTIATION KEY: Synopsis Draft

1. PROJECT OBJECTIVE & THEME
${data.content}

2. CORE FUNCTIONAL SPECIFICATIONS
* Software Ingestion Layer: Receives student requirements and processes localized state changes.
* Processing Intelligence pipeline: Optimizes computational bandwidth via server proxy hooks.
* UI Integration Level: Displays glassmorphic CSS styled widgets offering zero latency feedback.

3. METHODOLOGY BLUEPRINT
The development framework focuses on executing clean React states encapsulated in express containers. All private API structures remain server-authoritative to satisfy standard compliance security rules.`;
        setSynopsisText(syn_layout);
        setActiveTab("synopsis");
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoadingSynopsis(false);
    }
  };

  const handleCopySynopsis = () => {
    navigator.clipboard.writeText(synopsisText);
    showCopyNotif("synopsis");
  };

  const showCopyNotif = (t: "copied" | "latex" | "synopsis") => {
    setCopiedText(t);
    setTimeout(() => setCopiedText(null), 1800);
  };

  const generateLaTeXCode = () => {
    const formattedBullets = bullets.map(b => `  \\item ${b}`).join("\n");
    return `% LaTeX Resume Template Generated by ProjectPilot AI
\\documentclass[10pt,letterpaper]{article}
\\usepackage[utf8]{inputenc}
\\usepackage[margin=0.75in]{geometry}
\\usepackage{hyperref}
\\usepackage{titlesec}
\\usepackage{enumitem}

\\titleformat{\\section}{\\large\\bfseries}{}{0em}{}[\\titlerule]
\\titlespacing{\\section}{0pt}{10pt}{5pt}

\\begin{document}

\\begin{center}
    {\\LARGE \\textbf{${(name || "Student Name").toUpperCase()}}} \\\\ \\vspace{2pt}
    ${college || "Institution/University Name"} \\\\ \\vspace{2pt}
    Specialization: ${domain || "General Academics"} | Score: ${academicScore}
\\end{center}

\\section*{Academic Objective}
${summary || "Proactive and analytically-driven student."}

\\section*{Technical Thesis Portfolio}
\\textbf{Project Title:} ${projectTitle} \\\\
\\begin{itemize}[leftmargin=*]
${formattedBullets || "  \\item Key development bullet points here."}
\\end{itemize}

\\section*{Core Technical Skills}
${coreSkills || "Languages: Python, JavaScript, CSS, HTML, SQL"}

\\end{document}`;
  };

  const handleCopyLaTeX = () => {
    navigator.clipboard.writeText(generateLaTeXCode());
    showCopyNotif("latex");
  };

  const handleDownloadResumeDOCX = () => {
    let fullDoc = `<html><head><meta charset='utf-8'></head><body style='font-family: serif; padding: 40px;'>`;
    fullDoc += `<h1 style='text-align: center; text-transform: uppercase;'>${name || "Student Name"}</h1>`;
    fullDoc += `<p style='text-align: center; font-size: 13px;'>${college || "Institution Name"}</p>`;
    fullDoc += `<p style='text-align: center; font-size: 12px; font-style: italic;'>${domain} Specialization | ${academicScore}</p><hr/>`;
    
    fullDoc += `<h2>Professional Summary</h2>`;
    fullDoc += `<p style='line-height: 1.6; font-size: 13px;'>${summary}</p>`;
    
    fullDoc += `<h2>Technical Thesis Portfolio</h2>`;
    fullDoc += `<p style='font-weight: bold; font-size: 13px;'>Developed: "${projectTitle}"</p>`;
    fullDoc += `<ul style='font-size: 13px;'>`;
    bullets.forEach(b => {
      fullDoc += `<li style='line-height: 1.5; margin-bottom: 5px;'>${b}</li>`;
    });
    fullDoc += `</ul>`;
    
    if (coreSkills) {
      fullDoc += `<h2>Core Technical Skills</h2>`;
      fullDoc += `<p style='font-size: 13px;'>${coreSkills}</p>`;
    }
    
    fullDoc += `</body></html>`;

    const blob = new Blob([fullDoc], { type: "application/msword" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${(name || "student").toLowerCase().replace(/[^a-z0-0]/g, "_")}_technical_resume.doc`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadSynopsisDOCX = () => {
    let fullDoc = `<html><head><meta charset='utf-8'></head><body style='font-family: serif; padding: 40px;'>`;
    fullDoc += `<h2 style='text-align: center; color: #1e3a8a;'>PROJECT SYNOPSIS DOCUMENT PROPOSAL</h2><hr/>`;
    fullDoc += `<p><b>SUBJECT TOPIC:</b> ${projectTitle.toUpperCase()}</p>`;
    fullDoc += `<p><b>DOMAIN:</b> ${domain || "General Academics"}</p>`;
    fullDoc += `<p><b>DEVELOPED BY:</b> ${name || "Student Team"}</p>`;
    fullDoc += `<p><b>INSTITUTION:</b> ${college || "University"}</p><hr/><br/>`;

    // Split paragraphs
    const paragraphs = synopsisText.split("\n");
    paragraphs.forEach(p => {
      if (p.trim().length > 0) {
        if (p.includes("---") || p.includes("SUBJECT TOPIC") || p.includes("DOMAIN") || p.includes("ACADEMIC SUBSTANTIATION")) {
          return;
        }
        if (p.startsWith("1.") || p.startsWith("2.") || p.startsWith("3.")) {
          fullDoc += `<h3 style='color: rgb(30, 58, 138); margin-top:20px; font-family:serif;'>${p}</h3>`;
        } else if (p.startsWith("*")) {
          fullDoc += `<li style='margin-left:20px; font-family:serif; line-height: 1.5;'>${p.substring(1).trim()}</li>`;
        } else {
          fullDoc += `<p style='line-height: 1.6; font-family:serif;'>${p}</p>`;
        }
      }
    });

    fullDoc += `</body></html>`;

    const blob = new Blob([fullDoc], { type: "application/msword" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${projectTitle.toLowerCase().replace(/[^a-z0-0]/g, "_")}_project_synopsis.doc`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  // Modify individual bullet
  const handleBulletChange = (index: number, newValue: string) => {
    const updated = [...bullets];
    updated[index] = newValue;
    setBullets(updated);
  };

  return (
    <div className="space-y-6">
      {/* Header and Sub */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 border-b border-slate-800 pb-5">
        <div>
          <h1 className="text-2xl md:text-3xl font-bold text-white font-sans tracking-tight">
            Resume & Synopsis Documentation Helper
          </h1>
          <p className="text-sm text-slate-400 mt-1">
            Build high-growth technology resumes and generate standard initial Synopsis documents in seconds.
          </p>
        </div>

        {summary && activeTab === "resume" && (
          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded bg-blue-600 hover:bg-blue-500 text-xs text-white tracking-wide transition cursor-pointer shrink-0"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print Recruiter Sheet</span>
          </button>
        )}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        {/* Left Side: Parameters input */}
        <div className="lg:col-span-4 bg-slate-900/60 border border-slate-800 rounded-xl p-5 space-y-4">
          <h3 className="text-xs font-semibold text-slate-350 uppercase tracking-wider font-mono">
            Fill Credentials
          </h3>

          <div className="space-y-3">
            <div className="space-y-1">
              <label className="text-[11px] text-slate-400">Full Name</label>
              <input
                type="text"
                placeholder="Student Name e.g. Anjali Gupta"
                value={name}
                onChange={(e) => setName(e.target.value)}
                className="w-full bg-slate-950 border border-slate-800 text-slate-200 placeholder-slate-700 rounded-lg py-1.5 px-2.5 text-xs focus:outline-none focus:border-blue-500"
              />
            </div>

            <div className="space-y-1">
              <label className="text-[11px] text-slate-400 font-medium">Institution / University</label>
              <input
                type="text"
                placeholder="e.g. Stanford University"
                value={college}
                onChange={(e) => setCollege(e.target.value)}
                className="w-full bg-slate-950 border border-slate-800 text-slate-200 placeholder-slate-700 rounded-lg py-1.5 px-2.5 text-xs focus:outline-none focus:border-blue-500"
              />
            </div>

            <div className="space-y-1">
              <label className="text-[11px] text-slate-400 font-medium">Project Subject</label>
              <input
                type="text"
                placeholder="Project title..."
                value={projectTitle}
                onChange={(e) => setProjectTitle(e.target.value)}
                className="w-full bg-slate-950 border border-slate-800 text-slate-200 placeholder-slate-700 rounded-lg py-1.5 px-2.5 text-xs focus:outline-none focus:border-blue-500"
              />
            </div>

            <div className="grid grid-cols-2 gap-2">
              <div className="space-y-1">
                <label className="text-[11px] text-slate-400 font-medium font-sans">GPA/Score</label>
                <input
                  type="text"
                  placeholder="e.g. CGPA 9.2/10"
                  value={academicScore}
                  onChange={(e) => setAcademicScore(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-800 text-slate-300 placeholder-slate-700 rounded-lg py-1 px-2 text-xs focus:outline-none focus:border-blue-500"
                />
              </div>

              <div className="space-y-1">
                <label className="text-[11px] text-slate-400 font-medium">Domain</label>
                <input
                  type="text"
                  placeholder="e.g. Cyber Security"
                  value={domain}
                  onChange={(e) => setDomain(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-800 text-slate-300 placeholder-slate-700 rounded-lg py-1 px-2 text-xs focus:outline-none focus:border-blue-500"
                />
              </div>
            </div>

            <div className="space-y-1">
              <label className="text-[11px] text-slate-400">Teammate/My Coding Skills</label>
              <input
                type="text"
                placeholder="e.g. Python, Git, Docker, React, SQL"
                value={coreSkills}
                onChange={(e) => setCoreSkills(e.target.value)}
                className="w-full bg-slate-950 border border-slate-800 text-slate-200 placeholder-slate-700 rounded-lg py-1.5 px-2.5 text-xs focus:outline-none focus:border-blue-500"
              />
            </div>
          </div>

          <div className="pt-2 flex flex-col gap-2">
            <button
              onClick={handleGenerateResume}
              disabled={loading}
              className="w-full bg-gradient-to-r from-blue-700 to-indigo-700 hover:from-blue-600 hover:to-indigo-600 text-white rounded-lg py-2 font-bold text-xs flex items-center justify-center gap-1 cursor-pointer transition disabled:opacity-40"
            >
              {loading ? (
                <>
                  <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                  <span>Configuring CV elements...</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-3.5 h-3.5" />
                  <span>Build Recruiter CV Content</span>
                </>
              )}
            </button>

            <button
              onClick={handleGenerateSynopsis}
              disabled={loadingSynopsis}
              className="w-full bg-slate-950 hover:bg-slate-900 border border-slate-800 text-slate-300 hover:text-white py-2 rounded-lg text-xs font-semibold cursor-pointer transition flex items-center justify-center gap-1 disabled:opacity-40"
            >
              {loadingSynopsis ? (
                <>
                  <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                  <span>Formulating Abstract...</span>
                </>
              ) : (
                <>
                  <FileText className="w-3.5 h-3.5" />
                  <span>Draft Concept Synopsis</span>
                </>
              )}
            </button>
          </div>

          {/* CV Theme Picker (Visible when resume generated) */}
          {summary && (
            <div className="border-t border-slate-800 pt-3.5 space-y-2">
              <label className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider font-mono">CV Styling Blueprint</label>
              <div className="grid grid-cols-3 gap-1">
                {(["harvard", "tech", "executive"] as const).map((t) => (
                  <button
                    key={t}
                    onClick={() => setCvTheme(t)}
                    className={`px-2 py-1 rounded text-[10px] font-bold uppercase transition cursor-pointer text-center ${
                      cvTheme === t
                        ? "bg-blue-600/20 text-blue-400 border border-blue-500/30"
                        : "bg-slate-950 text-slate-500 hover:text-slate-300 border border-transparent"
                    }`}
                  >
                    {t}
                  </button>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Right Side: Tabbed Visual LaTeX Style Output mockup */}
        <div className="lg:col-span-8 space-y-4">
          {!summary && !synopsisText ? (
            <div className="border border-dashed border-slate-800 rounded-xl p-16 text-center bg-slate-950/20">
              <Award className="w-10 h-10 text-slate-700 mx-auto stroke-[1.5]" />
              <h3 className="text-slate-300 font-semibold mt-3 text-sm font-sans">Documentation Workstation Empty</h3>
              <p className="text-slate-500 text-xs max-w-sm mx-auto mt-1 leading-relaxed">
                Provide student credentials on the parameter side panel and press any generator option to construct beautiful LaTeX standard outputs.
              </p>
            </div>
          ) : (
            <div className="space-y-4">
              {/* Tab Selector header */}
              <div className="flex border-b border-slate-850 gap-2">
                {summary && (
                  <button
                    onClick={() => setActiveTab("resume")}
                    className={`pb-2.5 px-4 text-xs font-bold uppercase tracking-wider border-b-2 transition cursor-pointer ${
                      activeTab === "resume"
                        ? "border-blue-500 text-blue-400"
                        : "border-transparent text-slate-500 hover:text-slate-300"
                    }`}
                  >
                    📄 Recruiter CV Layout
                  </button>
                )}
                {synopsisText && (
                  <button
                    onClick={() => setActiveTab("synopsis")}
                    className={`pb-2.5 px-4 text-xs font-bold uppercase tracking-wider border-b-2 transition cursor-pointer ${
                      activeTab === "synopsis"
                        ? "border-blue-500 text-blue-400"
                        : "border-transparent text-slate-500 hover:text-slate-300"
                    }`}
                  >
                    📁 College Synopsis Draft
                  </button>
                )}
              </div>

              {/* 1. RESUME SHEET PANELS */}
              {activeTab === "resume" && summary && (
                <div className="space-y-4">
                  {/* Action Toolbar */}
                  <div className="bg-slate-900/60 border border-slate-800 rounded-xl px-4 py-3 flex flex-wrap gap-2 items-center justify-between">
                    <span className="text-xs font-mono text-slate-400">Layout: <strong className="text-slate-200 capitalize">{cvTheme} Serif</strong></span>

                    <div className="flex flex-wrap gap-2">
                      <button
                        onClick={() => setIsEditingResume(!isEditingResume)}
                        className={`flex items-center gap-1 px-2.5 py-1 rounded text-xs transition cursor-pointer ${
                          isEditingResume 
                            ? "bg-amber-600 text-white" 
                            : "bg-slate-950 hover:bg-slate-900 border border-slate-800 text-slate-300"
                        }`}
                      >
                        {isEditingResume ? <Eye className="w-3.5 h-3.5" /> : <Edit3 className="w-3.5 h-3.5" />}
                        <span>{isEditingResume ? "Preview Live" : "Edit Live"}</span>
                      </button>

                      <button
                        onClick={handleCopyLaTeX}
                        className="flex items-center gap-1 bg-slate-950 hover:bg-slate-900 border border-slate-800 text-slate-300 hover:text-white px-2.5 py-1 rounded text-xs cursor-pointer transition"
                      >
                        <FileCode className="w-3.5 h-3.5 text-indigo-400" />
                        <span>{copiedText === "latex" ? "Code Copied!" : "LaTeX Code"}</span>
                      </button>

                      <button
                        onClick={handleDownloadResumeDOCX}
                        className="flex items-center gap-1 bg-blue-600/10 hover:bg-blue-600/20 text-blue-400 border border-blue-500/20 px-2.5 py-1 rounded text-xs cursor-pointer transition"
                      >
                        <Download className="w-3.5 h-3.5" />
                        <span>DOCX File</span>
                      </button>
                    </div>
                  </div>

                  {/* Visual Sheets styling previewer */}
                  <div className={`shadow-2xl relative border p-8 rounded-xl transition duration-300 ${
                    cvTheme === "harvard" 
                      ? "bg-white border-slate-300 text-slate-900 font-serif" 
                      : cvTheme === "tech"
                      ? "bg-slate-950 border-slate-800 text-slate-100 font-sans"
                      : "bg-[#090d16] border-blue-900/40 text-slate-250 font-sans border-l-4 border-l-blue-600"
                  }`}>
                    {/* Floating watermark stamp */}
                    <div className={`absolute top-6 right-6 text-[9px] border rounded px-1.5 py-0.5 tracking-wider font-mono uppercase ${
                      cvTheme === "harvard" ? "text-slate-400 border-slate-200" : "text-slate-600 border-slate-800"
                    }`}>
                      PROJECTPILOT CV PROPOSAL
                    </div>

                    <div className={`text-center space-y-0.5 pb-4 border-b ${
                      cvTheme === "harvard" ? "border-slate-300" : "border-slate-800"
                    }`}>
                      <h2 className="text-xl font-bold tracking-tight uppercase">
                        {name || "Student Name"}
                      </h2>
                      <p className={`text-xs ${cvTheme === "harvard" ? "text-slate-500" : "text-slate-400"}`}>
                        {college || "Institution Name"}
                      </p>
                      <p className={`text-[11px] italic font-mono uppercase ${cvTheme === "harvard" ? "text-slate-400" : "text-slate-500"}`}>
                        {domain || "General"} Specialization | {academicScore || "Excellent standing"}
                      </p>
                    </div>

                    {/* Summary Section */}
                    <div className={`space-y-1.5 pt-4 border-b pb-4 ${
                      cvTheme === "harvard" ? "border-slate-300" : "border-slate-800/80"
                    }`}>
                      <h3 className={`text-xs font-bold uppercase tracking-wider font-sans`}>
                        Academic Summary
                      </h3>
                      {isEditingResume ? (
                        <textarea
                          value={summary}
                          onChange={(e) => setSummary(e.target.value)}
                          className="w-full text-xs bg-slate-900 text-slate-100 p-2 border border-slate-700 rounded focus:outline-none focus:border-blue-500 font-serif"
                          rows={3}
                        />
                      ) : (
                        <p className={`text-xs leading-relaxed ${cvTheme === "harvard" ? "text-slate-700 font-serif" : "text-slate-300"}`}>
                          {summary}
                        </p>
                      )}
                    </div>

                    {/* Project Bullet Section */}
                    <div className={`space-y-3 pt-4 border-b pb-4 ${
                      cvTheme === "harvard" ? "border-slate-300" : "border-slate-800/80"
                    }`}>
                      <h3 className="text-xs font-bold uppercase tracking-wider font-sans">
                        Technical Thesis Portfolio
                      </h3>
                      <div className="space-y-1">
                        <p className={`text-xs font-bold ${cvTheme === "harvard" ? "text-slate-900" : "text-white"}`}>
                          Thesis Title: "{projectTitle}"
                        </p>
                        
                        {isEditingResume ? (
                          <div className="space-y-2 pt-1 font-serif text-xs">
                            {bullets.map((b, i) => (
                              <div key={i} className="flex gap-2 items-center">
                                <span className="text-slate-500">{i+1}.</span>
                                <input
                                  type="text"
                                  value={b}
                                  onChange={(e) => handleBulletChange(i, e.target.value)}
                                  className="w-full bg-slate-900 text-slate-100 p-1.5 border border-slate-700 rounded text-xs focus:outline-none"
                                />
                              </div>
                            ))}
                          </div>
                        ) : (
                          <ul className={`list-disc pl-4 space-y-1.5 text-xs ${
                            cvTheme === "harvard" ? "text-slate-700 font-serif" : "text-slate-300"
                          }`}>
                            {bullets.map((bul, i) => (
                              <li key={i} className="leading-relaxed">
                                {bul}
                              </li>
                            ))}
                          </ul>
                        )}
                      </div>
                    </div>

                    {/* Skill sets */}
                    <div className="space-y-1.5 pt-4">
                      <h3 className="text-xs font-bold uppercase tracking-wider font-sans">
                        Core Skill Parameters
                      </h3>
                      {isEditingResume ? (
                        <input
                          type="text"
                          value={coreSkills}
                          onChange={(e) => setCoreSkills(e.target.value)}
                          className="w-full bg-slate-900 text-slate-100 p-1.5 border border-slate-700 rounded text-xs focus:outline-none focus:border-blue-500 font-sans"
                        />
                      ) : (
                        <p className={`text-xs ${
                          cvTheme === "harvard" ? "text-slate-800 font-serif" : "text-slate-300"
                        }`}>
                          {coreSkills || "Provide custom tech skills parameters on side panel."}
                        </p>
                      )}
                    </div>

                    {cvTheme === "harvard" && (
                      <div className="mt-8 pt-4 border-t border-slate-200 text-[8px] font-sans text-slate-400 text-center uppercase tracking-widest font-bold">
                        PREPARED & CONFIGURED 100% FREE BY PROJECTPILOT.AI
                      </div>
                    )}
                  </div>

                  {layoutAdvice && (
                    <div className="bg-blue-950/20 border border-blue-900/30 rounded-xl p-4 flex gap-3 text-xs text-blue-300">
                      <Info className="w-4 h-4 shrink-0 mt-0.5 text-blue-400" />
                      <div>
                        <strong className="block font-semibold text-blue-200">Coach's Structural Advice:</strong>
                        <p className="mt-0.5 leading-relaxed text-slate-400">{layoutAdvice}</p>
                      </div>
                    </div>
                  )}
                </div>
              )}

              {/* 2. SYNOPSIS COMPILING PANEL */}
              {activeTab === "synopsis" && synopsisText && (
                <div className="space-y-4">
                  {/* Action Toolbar */}
                  <div className="bg-slate-900/60 border border-slate-800 rounded-xl px-4 py-3 flex flex-wrap gap-2 items-center justify-between">
                    <span className="text-xs font-mono text-slate-400">Document Blueprint: <strong className="text-slate-200">Synopsis Draft Proposal</strong></span>

                    <div className="flex gap-2">
                      <button
                        onClick={() => setIsEditingSynopsis(!isEditingSynopsis)}
                        className={`flex items-center gap-1.5 px-3 py-1 rounded text-xs transition cursor-pointer ${
                          isEditingSynopsis
                            ? "bg-emerald-600 text-white"
                            : "bg-slate-950 hover:bg-slate-900 border border-slate-800 text-slate-300"
                        }`}
                      >
                        {isEditingSynopsis ? <Save className="w-3.5 h-3.5" /> : <Edit3 className="w-3.5 h-3.5" />}
                        <span>{isEditingSynopsis ? "Apply Edits" : "Edit Paragraphs"}</span>
                      </button>

                      <button
                        onClick={handleCopySynopsis}
                        className="text-xs text-slate-450 hover:text-white flex items-center gap-1.5 bg-slate-950 border border-slate-800 px-3 py-1 rounded cursor-pointer transition"
                      >
                        {copiedText === "synopsis" ? (
                          <Check className="w-3.5 h-3.5 text-emerald-400" />
                        ) : (
                          <Clipboard className="w-3.5 h-3.5" />
                        )}
                        <span>{copiedText === "synopsis" ? "Text Copied!" : "Copy Raw"}</span>
                      </button>

                      <button
                        onClick={handleDownloadSynopsisDOCX}
                        className="text-xs text-blue-400 hover:text-white flex items-center gap-1.5 bg-blue-600/10 hover:bg-blue-600/20 border border-blue-500/20 px-3 py-1 rounded cursor-pointer transition"
                      >
                        <Download className="w-3.5 h-3.5" />
                        <span>DOCX Word</span>
                      </button>
                    </div>
                  </div>

                  {/* Synopsis Editor / Viewer */}
                  <div className="bg-slate-950 border border-slate-800 rounded-xl overflow-hidden p-5">
                    {isEditingSynopsis ? (
                      <textarea
                        value={synopsisText}
                        onChange={(e) => setSynopsisText(e.target.value)}
                        className="w-full h-96 bg-slate-950 border-0 text-xs font-mono leading-relaxed text-slate-200 focus:outline-none resize-y p-1"
                      />
                    ) : (
                      <pre className="p-1 font-mono text-[10px] leading-relaxed text-slate-300 max-h-[500px] overflow-auto whitespace-pre-wrap">
                        {synopsisText}
                      </pre>
                    )}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* Expanded Section: ATS & Layout Guidelines for Final Year Students */}
          <div className="bg-[#090d16]/80 p-5 rounded-xl border border-slate-800 space-y-4">
            <div className="flex gap-2 items-center text-slate-200">
              <Award className="w-4 h-4 text-amber-500" />
              <h4 className="text-xs font-bold uppercase tracking-wider font-sans">ATS & Recruiter Compliance Optimizer</h4>
            </div>
            
            <p className="text-[11px] text-slate-400 leading-relaxed">
              University graduates frequently struggle with getting their resumes parsed by ATS (Applicant Tracking Systems) software. Follow these structural standards compiled by ProjectPilot coach advisors:
            </p>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-1">
              <div className="bg-slate-950/60 rounded-lg p-3 border border-slate-850 space-y-2">
                <span className="text-[10px] font-bold text-blue-400 uppercase tracking-widest font-mono block">Action Verbs Library</span>
                <p className="text-[10.5px] text-slate-500 leading-snug">
                  Swap passive descriptions for modern action elements to showcase direct execution:
                </p>
                <div className="flex flex-wrap gap-1">
                  {["Engineered", "Synthesized", "Optimized", "Spearheaded", "Formulated", "Leveraged", "Automated", "Pioneered"].map((verb) => (
                    <span key={verb} className="bg-slate-900 border border-slate-850 px-1.5 py-0.5 rounded text-[10px] font-mono text-slate-350 select-none">
                      {verb}
                    </span>
                  ))}
                </div>
              </div>

              <div className="bg-slate-950/60 rounded-lg p-3 border border-slate-850 space-y-2">
                <span className="text-[10px] font-bold text-amber-400 uppercase tracking-widest font-mono block">Resume Format Rules</span>
                <ul className="text-[10.5px] text-slate-450 space-y-1.5 list-disc pl-3">
                  <li><strong>Single Page Bounds:</strong> Undergrad applications must fit exclusively within 1 page.</li>
                  <li><strong>Format Exports:</strong> PDF is best, but keep a LaTeX source as backup for technical submissions.</li>
                  <li><strong>No Custom Bars:</strong> Simple top headers outperform double vertical bar layouts in keyword parsers.</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
